version: '3.7'

services:
  backend:
    build: ./backend/simpleapi/simple-api-student
    container_name: backend
    networks:
      - app-network
    depends_on:
      - database

  database:
    container_name: database
    build: ./database
    networks:
      - app-network

  httpd:
    build: ./http
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
